-- =========================================
-- SECTION: BASIC SELECT & FILTERING
-- PROJECT: HEALTHCARE SQL ANALYSIS
-- =========================================

-- SHOW ALL PATIENTS
-- THIS QUERY DISPLAYS ALL PATIENT RECORDS AVAILABLE IN THE DATABASE.

SELECT * FROM PATIENTS;

-- SHOW ALL DOCTORS
-- THIS QUERY DISPLAYS ALL DOCTOR DETAILS STORED IN THE SYSTEM.

SELECT * FROM DOCTORS;

-- SHOW ALL APPOINTMENTS
-- THIS QUERY DISPLAYS ALL APPOINTMENTS BOOKED BY PATIENTS.

SELECT * FROM APPOINTMENTS;

-- SHOW ALL TREATMENTS
-- THIS QUERY DISPLAYS ALL TREATMENTS PROVIDED DURING APPOINTMENTS.

SELECT * FROM TREATMENTS;

-- SHOW ALL BILLING RECORDS
-- THIS QUERY DISPLAYS ALL BILLING AND PAYMENT DETAILS.

SELECT * FROM BILLING;

-- DISPLAY PATIENT NAME AND AGE
-- THIS QUERY SHOWS PATIENT FULL NAME AND CALCULATES THEIR CURRENT AGE.

SELECT
    FIRST_NAME || ' ' || LAST_NAME AS PATIENT_NAME,
    TRUNC(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH) / 12) AS AGE
FROM PATIENTS;

-- DISPLAY DOCTOR NAME AND SPECIALIZATION
-- THIS QUERY SHOWS DOCTOR NAME ALONG WITH THEIR MEDICAL SPECIALIZATION.

SELECT
    FIRST_NAME || ' ' || LAST_NAME AS DOCTORS_NAME,
    SPECIALIZATION
FROM DOCTORS;

-- SHOW APPOINTMENTS WITH STATUS = 'COMPLETED'
-- THIS QUERY FILTERS ONLY THOSE APPOINTMENTS THAT WERE COMPLETED.

SELECT * FROM APPOINTMENTS
WHERE STATUS = 'Completed';

-- SHOW APPOINTMENTS WITH STATUS = 'CANCELLED'
-- THIS QUERY FILTERS APPOINTMENTS THAT WERE CANCELLED.

SELECT * FROM APPOINTMENTS
WHERE STATUS = 'Cancelled';

-- SHOW TREATMENTS COSTING MORE THAN 5000
-- THIS QUERY IDENTIFIES HIGH-COST OR EXPENSIVE TREATMENTS.

SELECT * FROM TREATMENTS
WHERE COST > 3500;

-- SHOW PAID BILLS
-- THIS QUERY SHOWS BILLS WHERE PAYMENT WAS SUCCESSFUL.

SELECT * FROM BILLING
WHERE PAYMENT_STATUS = 'Paid';

-- SHOW UNPAID BILLS
-- THIS QUERY SHOWS BILLS WHERE PAYMENT FAILED OR IS PENDING.

SELECT * FROM BILLING
WHERE PAYMENT_STATUS = 'Failed';

-- SHOW BILLING RECORDS PAID VIA UPI
-- THIS QUERY FILTERS BILLING RECORDS BY PAYMENT METHOD.

SELECT * FROM BILLING
WHERE PAYMENT_METHOD = 'Credit Card';

-- SHOW DOCTORS WITH MORE THAN 10 YEARS OF EXPERIENCE
-- THIS QUERY IDENTIFIES SENIOR AND EXPERIENCED DOCTORS.

SELECT * FROM DOCTORS
WHERE YEARS_EXPERIENCE > 10;

-- SHOW PATIENTS OLDER THAN 60
-- THIS QUERY IDENTIFIES ELDERLY PATIENTS.

SELECT * FROM PATIENTS
WHERE MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH) / 12 > 60;

-- SHOW PATIENTS FROM A SPECIFIC CITY
-- CITY DATA IS NOT AVAILABLE, SO INSURANCE PROVIDER IS USED AS AN ALTERNATIVE.

SELECT * FROM PATIENTS
WHERE INSURANCE_PROVIDER = 'HealthIndia';

-- SHOW DOCTORS FROM A SPECIFIC HOSPITAL
-- THIS QUERY FILTERS DOCTORS WORKING IN A PARTICULAR HOSPITAL BRANCH.

SELECT * FROM DOCTORS
WHERE HOSPITAL_BRANCH = 'Central Hospital';

-- SHOW APPOINTMENTS AFTER A GIVEN DATE
-- THIS QUERY DISPLAYS APPOINTMENTS THAT OCCURRED AFTER A SPECIFIC DATE.

SELECT * FROM APPOINTMENTS
WHERE APPOINTMENT_DATE > DATE '2023-01-15'
ORDER BY APPOINTMENT_DATE;

-- SHOW DISTINCT PAYMENT METHODS
-- THIS QUERY LISTS ALL UNIQUE PAYMENT METHODS USED.

SELECT DISTINCT PAYMENT_METHOD
FROM BILLING;

-- SHOW DISTINCT DOCTOR SPECIALIZATIONS
-- THIS QUERY LISTS ALL UNIQUE MEDICAL SPECIALIZATIONS AVAILABLE.

SELECT DISTINCT SPECIALIZATION
FROM DOCTORS;
