-- =========================================
-- SECTION: AGGREGATE FUNCTIONS
-- PROJECT: HEALTHCARE SQL ANALYSIS
-- =========================================

-- TOTAL NUMBER OF PATIENTS
-- THIS QUERY COUNTS HOW MANY PATIENTS ARE REGISTERED IN THE SYSTEM.

SELECT COUNT(*) FROM PATIENTS;

-- TOTAL NUMBER OF DOCTORS
-- THIS QUERY COUNTS THE TOTAL NUMBER OF DOCTORS AVAILABLE.

SELECT COUNT(*) FROM DOCTORS;

-- TOTAL NUMBER OF APPOINTMENTS
-- THIS QUERY COUNTS ALL APPOINTMENTS BOOKED BY PATIENTS.

SELECT COUNT(*) FROM APPOINTMENTS;

-- TOTAL NUMBER OF TREATMENTS
-- THIS QUERY COUNTS ALL TREATMENTS PROVIDED.

SELECT COUNT(*) FROM TREATMENTS;

-- TOTAL NUMBER OF BILLS
-- THIS QUERY COUNTS ALL BILLING RECORDS GENERATED.

SELECT COUNT(*) FROM BILLING;

-- TOTAL HEALTHCARE REVENUE
-- THIS QUERY CALCULATES THE TOTAL REVENUE GENERATED FROM ALL BILLS.

SELECT SUM(AMOUNT) AS HEALTHCARE_REVENUE FROM BILLING;

-- AVERAGE PATIENT AGE
-- THIS QUERY CALCULATES THE AVERAGE AGE OF ALL PATIENTS.

SELECT TRUNC(AVG(MONTHS_BETWEEN(SYSDATE,DATE_OF_BIRTH)/12)) AS AVERAGE_PATIENTS_AGE
FROM PATIENTS;

-- MAXIMUM TREATMENT COST
-- THIS QUERY FINDS THE MOST EXPENSIVE TREATMENT COST.

SELECT MAX(COST) AS MAXIMUM_TREATMENT_COST FROM TREATMENTS;


-- MINIMUM TREATMENT COST
-- THIS QUERY FINDS THE LEAST EXPENSIVE TREATMENT COST.

SELECT MIN(COST) AS MINIMUM_TREATMENT_COST FROM TREATMENTS;

-- AVERAGE TREATMENT COST
-- THIS QUERY CALCULATES THE AVERAGE COST OF ALL TREATMENTS.

SELECT AVG(COST) AS AVERAGE_TREATMENT_COST FROM TREATMENTS;

-- HIGHEST BILL AMOUNT
-- THIS QUERY IDENTIFIES THE HIGHEST BILL AMOUNT GENERATED.

SELECT MAX(AMOUNT) AS HIGHEST_BILL_AMOUNT FROM BILLING;

-- LOWEST BILL AMOUNT
-- THIS QUERY IDENTIFIES THE LOWEST BILL AMOUNT GENERATED.

SELECT MIN(AMOUNT) AS LOWEST_BILL_AMOUNT FROM BILLING;

-- AVERAGE BILL AMOUNT
-- THIS QUERY CALCULATES THE AVERAGE AMOUNT OF ALL BILLS.

SELECT AVG(AMOUNT) AS AVERAGE_BILL_AMOUNT FROM BILLING;

-- COUNT OF COMPLETED APPOINTMENTS
-- THIS QUERY COUNTS HOW MANY APPOINTMENTS WERE SUCCESSFULLY COMPLETED.

SELECT COUNT(*) AS COMPLETED_APPOINTMENTS
FROM APPOINTMENTS
WHERE STATUS = 'Completed';

-- COUNT OF CANCELLED APPOINTMENTS
-- THIS QUERY COUNTS HOW MANY APPOINTMENTS WERE CANCELLED.

SELECT COUNT(*) AS CANCELLED_APPOINTMENTS
FROM APPOINTMENTS
WHERE STATUS = 'Cancelled';

-- COUNT OF PAID BILLS
-- THIS QUERY COUNTS BILLS WHERE PAYMENT WAS SUCCESSFUL.

SELECT COUNT(*) AS PAID_BILLS
FROM BILLING
WHERE PAYMENT_STATUS = 'Paid';

-- COUNT OF UNPAID BILLS
-- THIS QUERY COUNTS BILLS WHERE PAYMENT FAILED OR WAS NOT DONE.

SELECT COUNT(*) AS UNPAID_BILLS
FROM BILLING
WHERE PAYMENT_STATUS = 'Failed';

-- TOTAL REVENUE FROM PAID BILLS
-- THIS QUERY CALCULATES REVENUE GENERATED ONLY FROM PAID BILLS.

SELECT SUM(AMOUNT) AS TOTAL_REVENUE_OF_PAID_BILLS
FROM BILLING
WHERE PAYMENT_STATUS = 'Paid';

-- TOTAL REVENUE FROM UNPAID BILLS
-- THIS QUERY CALCULATES POTENTIAL REVENUE LOST FROM UNPAID BILLS.

SELECT SUM(AMOUNT) AS TOTAL_REVENUE_OF_UNPAID_BILLS
FROM BILLING
WHERE PAYMENT_STATUS = 'Failed';

-- NUMBER OF UNIQUE PAYMENT METHODS
-- THIS QUERY COUNTS HOW MANY DIFFERENT PAYMENT METHODS ARE USED.

SELECT PAYMENT_METHOD,
       COUNT(PAYMENT_METHOD) AS NO_OF_UNIQUE_PAYMENT_METHODS
FROM BILLING
GROUP BY PAYMENT_METHOD;
