-- =========================================
-- SECTION: GROUP BY & HAVING
-- PROJECT: HEALTHCARE SQL ANALYSIS
-- =========================================

-- PATIENTS COUNT BY CITY
-- CITY DATA IS NOT AVAILABLE, SO GENDER IS USED AS AN ALTERNATIVE GROUPING.

SELECT GENDER, COUNT(*)
FROM PATIENTS
GROUP BY GENDER;

-- DOCTORS COUNT BY SPECIALIZATION
-- THIS QUERY COUNTS DOCTORS IN EACH SPECIALIZATION.

SELECT SPECIALIZATION, COUNT(*)
FROM DOCTORS
GROUP BY SPECIALIZATION;

-- APPOINTMENTS COUNT PER DOCTOR
-- THIS QUERY COUNTS HOW MANY APPOINTMENTS EACH DOCTOR HAS.

SELECT DOCTOR_ID, COUNT(*)
FROM APPOINTMENTS
GROUP BY DOCTOR_ID
ORDER BY DOCTOR_ID;

-- APPOINTMENTS COUNT PER PATIENT
-- THIS QUERY COUNTS HOW MANY APPOINTMENTS EACH PATIENT HAS.

SELECT PATIENT_ID, COUNT(*)
FROM APPOINTMENTS
GROUP BY PATIENT_ID
ORDER BY PATIENT_ID;

-- COMPLETED APPOINTMENTS PER DOCTOR
-- THIS QUERY COUNTS COMPLETED APPOINTMENTS FOR EACH DOCTOR.

SELECT DOCTOR_ID, COUNT(*) AS COMPLETED_APPOINTMNETS
FROM APPOINTMENTS
WHERE STATUS = 'Completed'
GROUP BY DOCTOR_ID;

-- CANCELLED APPOINTMENTS PER DOCTOR
-- THIS QUERY COUNTS CANCELLED APPOINTMENTS FOR EACH DOCTOR.

SELECT DOCTOR_ID, COUNT(*) AS CANCELLED_APPOINTMNETS
FROM APPOINTMENTS
WHERE STATUS = 'Cancelled'
GROUP BY DOCTOR_ID;

-- TREATMENTS COUNT PER APPOINTMENT
-- THIS QUERY COUNTS HOW MANY TREATMENTS WERE DONE IN EACH APPOINTMENT.

SELECT APPOINTMENT_ID, COUNT(*) AS TREATMENT_COUNT
FROM TREATMENTS
GROUP BY APPOINTMENT_ID;

-- AVERAGE TREATMENT COST PER TREATMENT TYPE
-- THIS QUERY CALCULATES AVERAGE COST FOR EACH TREATMENT TYPE.

SELECT TREATMENT_TYPE, ROUND(AVG(COST),2)
FROM TREATMENTS
GROUP BY TREATMENT_TYPE;

-- REVENUE BY PAYMENT METHOD
-- THIS QUERY CALCULATES TOTAL REVENUE FOR EACH PAYMENT METHOD.

SELECT PAYMENT_METHOD, SUM(AMOUNT) AS TOTAL_REVENUE_BY_PYM
FROM BILLING
GROUP BY PAYMENT_METHOD;

-- REVENUE BY PAYMENT STATUS
-- THIS QUERY CALCULATES TOTAL REVENUE BY PAYMENT STATUS.

SELECT PAYMENT_STATUS, SUM(AMOUNT) AS TOTAL_REVENUE_BY_PYS
FROM BILLING
GROUP BY PAYMENT_STATUS;

-- DOCTORS WITH MORE THAN 20 APPOINTMENTS
-- THIS QUERY IDENTIFIES DOCTORS HAVING HIGH NUMBER OF APPOINTMENTS.

SELECT DOCTOR_ID, COUNT(*) AS APPOINTMENT
FROM APPOINTMENTS
GROUP BY DOCTOR_ID
HAVING COUNT(*) > 20
ORDER BY DOCTOR_ID;

-- PATIENTS WITH MORE THAN 1 APPOINTMENT
-- THIS QUERY IDENTIFIES REPEAT PATIENTS.

SELECT PATIENT_ID, COUNT(*) AS APPOINTMENT
FROM APPOINTMENTS
GROUP BY PATIENT_ID
HAVING COUNT(*) > 1
ORDER BY PATIENT_ID;

-- CITIES WITH MORE THAN 10 PATIENTS
-- CITY DATA IS NOT AVAILABLE, SO INSURANCE PROVIDER IS USED AS AN ALTERNATIVE.

SELECT INSURANCE_PROVIDER, COUNT(*) AS PATIENTS_COUNT
FROM PATIENTS
GROUP BY INSURANCE_PROVIDER
HAVING COUNT(*) > 10;

-- SPECIALIZATIONS WITH MORE THAN 5 DOCTORS
-- THIS QUERY IDENTIFIES SPECIALIZATIONS WITH HIGH DOCTOR COUNT.

SELECT SPECIALIZATION, COUNT(*) AS DOCTOR_COUNT
FROM DOCTORS
GROUP BY SPECIALIZATION
HAVING COUNT(*) >= 5;

-- TREATMENT TYPES WITH HIGH AVERAGE COST
-- THIS QUERY FINDS TREATMENT TYPES COSTLIER THAN OVERALL AVERAGE.

SELECT TREATMENT_TYPE, AVG(COST) AS AVG_COST
FROM TREATMENTS
GROUP BY TREATMENT_TYPE
HAVING AVG(COST) > (
    SELECT AVG(COST) FROM TREATMENTS
);

-- DOCTORS WITH HIGH CANCELLATION RATE
-- THIS QUERY COUNTS HOW MANY APPOINTMENTS EACH DOCTOR CANCELLED.

SELECT DOCTOR_ID, COUNT(*) AS CANCELLATION_RATE
FROM APPOINTMENTS
WHERE STATUS = 'Cancelled'
GROUP BY DOCTOR_ID
ORDER BY DOCTOR_ID;

-- PATIENTS WITH FREQUENT VISITS
-- THIS QUERY IDENTIFIES PATIENTS WITH MULTIPLE VISITS.

SELECT PATIENT_ID, COUNT(*) AS FREQUENT_VISIT
FROM APPOINTMENTS
GROUP BY PATIENT_ID
HAVING COUNT(*) > 1
ORDER BY PATIENT_ID;

-- MOST COMMONLY USED PAYMENT METHOD
-- THIS QUERY IDENTIFIES THE MOST FREQUENT PAYMENT METHOD USED.

SELECT PAYMENT_METHOD, USAGE_COUNT
FROM (
    SELECT PAYMENT_METHOD, COUNT(*) AS USAGE_COUNT
    FROM BILLING
    GROUP BY PAYMENT_METHOD
    ORDER BY USAGE_COUNT DESC
)
WHERE ROWNUM = 1;

-- HIGHEST EARNING PAYMENT METHOD
-- THIS QUERY IDENTIFIES THE PAYMENT METHOD GENERATING HIGHEST REVENUE.

SELECT PAYMENT_METHOD, TOTAL_REVENUE
FROM (
    SELECT PAYMENT_METHOD, SUM(AMOUNT) AS TOTAL_REVENUE
    FROM BILLING
    GROUP BY PAYMENT_METHOD
    ORDER BY TOTAL_REVENUE DESC
)
WHERE ROWNUM = 1;

-- APPOINTMENTS PER DAY
-- THIS QUERY COUNTS NUMBER OF APPOINTMENTS FOR EACH DAY.

SELECT APPOINTMENT_DATE, COUNT(*) AS DAILY_APPOINTMENTS
FROM APPOINTMENTS
GROUP BY APPOINTMENT_DATE;
