-- =========================================
-- SECTION: JOINS
-- PROJECT: HEALTHCARE SQL ANALYSIS
-- =========================================

-- PATIENT NAME WITH APPOINTMENT DATE
-- THIS QUERY SHOWS PATIENT NAMES ALONG WITH THEIR APPOINTMENT DATES.

SELECT 
    P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    A.APPOINTMENT_DATE
FROM PATIENTS P JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID;

-- DOCTOR NAME WITH APPOINTMENT DATE
-- THIS QUERY SHOWS DOCTOR NAMES ALONG WITH APPOINTMENT DATES.

SELECT 
    D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
    A.APPOINTMENT_DATE
FROM DOCTORS D JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID;

-- PATIENT NAME, DOCTOR NAME, APPOINTMENT DATE
-- THIS QUERY DISPLAYS PATIENT NAME, DOCTOR NAME, AND APPOINTMENT DATE TOGETHER.

SELECT
    P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
    A.APPOINTMENT_DATE
FROM PATIENTS P JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN DOCTORS D 
ON D.DOCTOR_ID = A.DOCTOR_ID;

-- APPOINTMENT DETAILS WITH PATIENT CITY
-- CITY DATA IS NOT AVAILABLE, SO INSURANCE PROVIDER IS USED AS AN ALTERNATIVE.

SELECT 
    P.PATIENT_ID, A.APPOINTMENT_ID,
    A.DOCTOR_ID, A.APPOINTMENT_DATE,
    A.REASON_FOR_VISIT, A.STATUS,
    P.INSURANCE_PROVIDER
FROM APPOINTMENTS A JOIN PATIENTS P
ON A.PATIENT_ID = P.PATIENT_ID;

-- APPOINTMENT DETAILS WITH DOCTOR SPECIALIZATION
-- THIS QUERY SHOWS APPOINTMENT DETAILS ALONG WITH DOCTOR SPECIALIZATION.

SELECT 
    D.DOCTOR_ID, A.APPOINTMENT_ID,
    A.PATIENT_ID, A.APPOINTMENT_DATE,
    A.REASON_FOR_VISIT, A.STATUS,
    D.SPECIALIZATION
FROM APPOINTMENTS A JOIN DOCTORS D
ON D.DOCTOR_ID = A.DOCTOR_ID;

-- TREATMENT DETAILS WITH APPOINTMENT DATE
-- THIS QUERY DISPLAYS TREATMENT DETAILS ALONG WITH APPOINTMENT DATE.

SELECT
    T.APPOINTMENT_ID, A.APPOINTMENT_DATE,
    T.TREATMENT_ID, T.TREATMENT_TYPE,
    T.DESCRIPTION, T.COST,
    T.TREATMENT_DATE
FROM TREATMENTS T JOIN APPOINTMENTS A
ON T.APPOINTMENT_ID = A.APPOINTMENT_ID;

-- TREATMENT DETAILS WITH PATIENT NAME
-- THIS QUERY SHOWS TREATMENT DETAILS ALONG WITH PATIENT NAME.

SELECT
    P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME, T.APPOINTMENT_ID,
    T.TREATMENT_ID, T.TREATMENT_TYPE,
    T.DESCRIPTION, T.COST,
    T.TREATMENT_DATE
FROM TREATMENTS T JOIN APPOINTMENTS A
ON T.APPOINTMENT_ID = A.APPOINTMENT_ID
JOIN PATIENTS P
ON P.PATIENT_ID = A.PATIENT_ID;

-- TREATMENT DETAILS WITH DOCTOR NAME
-- THIS QUERY SHOWS TREATMENT DETAILS ALONG WITH DOCTOR NAME.

SELECT
    D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME, T.APPOINTMENT_ID,
    T.TREATMENT_ID, T.TREATMENT_TYPE,
    T.DESCRIPTION, T.COST,
    T.TREATMENT_DATE
FROM TREATMENTS T JOIN APPOINTMENTS A
ON T.APPOINTMENT_ID = A.APPOINTMENT_ID
JOIN DOCTORS D
ON D.DOCTOR_ID = A.DOCTOR_ID;

-- DOCTORS AND TOTAL TREATMENTS PERFORMED
-- THIS QUERY COUNTS TOTAL TREATMENTS PERFORMED BY EACH DOCTOR.

SELECT 
    D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME, D.DOCTOR_ID,
    COUNT(*) AS TOTAL_TREATMENT_PERFORMED
FROM DOCTORS D JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN TREATMENTS T
ON T.APPOINTMENT_ID = A.APPOINTMENT_ID
GROUP BY D.DOCTOR_ID, D.FIRST_NAME, D.LAST_NAME
ORDER BY DOCTOR_ID;

-- PATIENTS AND TOTAL TREATMENTS RECEIVED
-- THIS QUERY COUNTS TOTAL TREATMENTS RECEIVED BY EACH PATIENT.

SELECT 
    P.PATIENT_ID, P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    COUNT(*) AS TOTAL_TREATMENT_RECEIVED
FROM PATIENTS P JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN TREATMENTS T
ON T.APPOINTMENT_ID = A.APPOINTMENT_ID
GROUP BY P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME
ORDER BY PATIENT_ID;

-- APPOINTMENTS WITH MULTIPLE TREATMENTS
-- THIS QUERY IDENTIFIES APPOINTMENTS HAVING MORE THAN ONE TREATMENT.

SELECT 
    A.APPOINTMENT_ID, A.PATIENT_ID,
    COUNT(T.TREATMENT_ID) AS TREATMENT_COUNT
FROM APPOINTMENTS A JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY A.APPOINTMENT_ID, A.PATIENT_ID
HAVING COUNT(T.TREATMENT_ID) > 1
ORDER BY A.PATIENT_ID;

-- DOCTORS WHO HANDLED MOST PATIENTS
-- THIS QUERY IDENTIFIES THE DOCTOR WHO HANDLED THE MOST COMPLETED APPOINTMENTS.

SELECT * FROM (
    SELECT
        D.DOCTOR_ID, D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
        COUNT(*) AS NO_OF_PATIENTS
    FROM DOCTORS D JOIN APPOINTMENTS A
    ON D.DOCTOR_ID = A.DOCTOR_ID
    WHERE A.STATUS = 'Completed'
    GROUP BY D.DOCTOR_ID, D.FIRST_NAME, D.LAST_NAME
    ORDER BY NO_OF_PATIENTS DESC
)
WHERE ROWNUM = 1;

-- PATIENTS TREATED BY MULTIPLE DOCTORS
-- THIS QUERY IDENTIFIES PATIENTS WHO VISITED MORE THAN ONE DOCTOR.

SELECT 
    P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME, P.PATIENT_ID,
    COUNT(DISTINCT A.DOCTOR_ID) AS DOCTORS_TREATMENTED
FROM PATIENTS P JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME
HAVING COUNT(DISTINCT A.DOCTOR_ID) > 1
ORDER BY P.PATIENT_ID;

-- DOCTOR-WISE COMPLETED APPOINTMENTS
-- THIS QUERY COUNTS COMPLETED APPOINTMENTS FOR EACH DOCTOR.

SELECT 
    D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME, D.DOCTOR_ID,
    COUNT(*) AS TOTAL_TREATMENT_PERFORMED
FROM DOCTORS D JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
WHERE A.STATUS = 'Completed'
GROUP BY D.DOCTOR_ID, D.FIRST_NAME, D.LAST_NAME
ORDER BY DOCTOR_ID;

-- DOCTOR-WISE CANCELLED APPOINTMENTS
-- THIS QUERY COUNTS CANCELLED APPOINTMENTS FOR EACH DOCTOR.

SELECT 
    D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME, D.DOCTOR_ID,
    COUNT(*) AS TOTAL_TREATMENT_PERFORMED
FROM DOCTORS D JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
WHERE A.STATUS = 'Cancelled'
GROUP BY D.DOCTOR_ID, D.FIRST_NAME, D.LAST_NAME
ORDER BY DOCTOR_ID;

-- PATIENT-WISE APPOINTMENT HISTORY
-- THIS QUERY SHOWS APPOINTMENT HISTORY FOR EACH PATIENT.

SELECT
    P.PATIENT_ID, P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    A.APPOINTMENT_ID, A.APPOINTMENT_DATE,
    A.REASON_FOR_VISIT, A.STATUS
FROM PATIENTS P JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
WHERE A.STATUS = 'Completed'
ORDER BY P.PATIENT_ID, A.APPOINTMENT_DATE;

-- DOCTOR EXPERIENCE VS APPOINTMENT COUNT
-- THIS QUERY COMPARES DOCTOR EXPERIENCE WITH NUMBER OF APPOINTMENTS.

SELECT
    D.DOCTOR_ID, D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
    D.YEARS_EXPERIENCE, COUNT(A.APPOINTMENT_ID) AS APPOINTMENT_COUNT
FROM DOCTORS D LEFT JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
GROUP BY D.DOCTOR_ID, D.FIRST_NAME, D.LAST_NAME, D.YEARS_EXPERIENCE
ORDER BY D.YEARS_EXPERIENCE, APPOINTMENT_COUNT DESC;

-- TREATMENT COST PER DOCTOR
-- THIS QUERY CALCULATES TOTAL TREATMENT COST PER DOCTOR.

SELECT
    D.DOCTOR_ID, D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
    SUM(T.COST) AS TREATMENT_COST
FROM DOCTORS D JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY D.DOCTOR_ID, D.FIRST_NAME, D.LAST_NAME
ORDER BY DOCTOR_ID;

-- TREATMENT COST PER PATIENT
-- THIS QUERY CALCULATES TOTAL TREATMENT COST PER PATIENT.

SELECT
    P.PATIENT_ID, P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    T.TREATMENT_TYPE, SUM(B.AMOUNT) AS TREATMENT_COST
FROM PATIENTS P JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN TREATMENTS T
ON T.APPOINTMENT_ID = A.APPOINTMENT_ID
JOIN BILLING B
ON B.TREATMENT_ID = T.TREATMENT_ID
GROUP BY P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, T.TREATMENT_TYPE;

-- MOST EXPENSIVE TREATMENT PER DOCTOR
-- THIS QUERY FINDS THE MOST EXPENSIVE TREATMENT GIVEN BY EACH DOCTOR.

SELECT
    D.DOCTOR_ID, D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
    T.TREATMENT_TYPE, T.COST AS MOST_EXPENSIVE_TREAMENT
FROM DOCTORS D JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
WHERE T.COST = (
    SELECT MAX(T1.COST)
    FROM APPOINTMENTS A1
    JOIN TREATMENTS T1
    ON A1.APPOINTMENT_ID = T1.APPOINTMENT_ID
    WHERE A1.DOCTOR_ID = D.DOCTOR_ID
)
ORDER BY DOCTOR_ID;

-- MOST EXPENSIVE TREATMENT PER PATIENT
-- THIS QUERY FINDS THE MOST EXPENSIVE TREATMENT RECEIVED BY EACH PATIENT.

SELECT
    P.PATIENT_ID, P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    T.TREATMENT_TYPE, T.COST AS MOST_EXPENSIVE_TREAMENT
FROM PATIENTS P JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
WHERE T.COST = (
    SELECT MAX(T1.COST)
    FROM APPOINTMENTS A1
    JOIN TREATMENTS T1
    ON A1.APPOINTMENT_ID = T1.APPOINTMENT_ID
    WHERE A1.PATIENT_ID = P.PATIENT_ID
)
ORDER BY PATIENT_ID;

-- DOCTORS WITHOUT ANY APPOINTMENTS
-- THIS QUERY IDENTIFIES DOCTORS WHO NEVER HAD ANY APPOINTMENTS.

SELECT
    D.DOCTOR_ID, D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME
FROM DOCTORS D LEFT JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
WHERE A.APPOINTMENT_ID IS NULL
GROUP BY D.DOCTOR_ID, D.FIRST_NAME, D.LAST_NAME;

-- PATIENTS WITHOUT ANY APPOINTMENTS
-- THIS QUERY IDENTIFIES PATIENTS WHO NEVER BOOKED ANY APPOINTMENTS.

SELECT
    P.PATIENT_ID, P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME
FROM PATIENTS P LEFT JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
WHERE A.APPOINTMENT_ID IS NULL
GROUP BY P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME;

-- APPOINTMENTS WITHOUT TREATMENTS
-- THIS QUERY IDENTIFIES APPOINTMENTS WHERE NO TREATMENT WAS GIVEN.

SELECT
    A.PATIENT_ID, A.DOCTOR_ID,
    A.APPOINTMENT_ID, A.APPOINTMENT_DATE,
    A.REASON_FOR_VISIT
FROM APPOINTMENTS A LEFT JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
WHERE T.TREATMENT_ID IS NULL;

-- FULL CLINICAL FLOW (PATIENTS → APPOINTMENTS → TREATMENTS)
-- THIS QUERY SHOWS COMPLETE CLINICAL FLOW FROM PATIENT TO TREATMENT.

SELECT 
    P.PATIENT_ID, P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    P.GENDER, P.DATE_OF_BIRTH,
    D.DOCTOR_ID, D.FIRST_NAME || ' ' || D.LAST_NAME AS DOCTOR_NAME,
    D.PHONE_NUMBER,
    A.APPOINTMENT_ID, A.APPOINTMENT_DATE, A.REASON_FOR_VISIT,
    T.TREATMENT_ID, T.TREATMENT_TYPE, T.TREATMENT_DATE, T.COST
FROM PATIENTS P JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN DOCTORS D
ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN TREATMENTS T
ON T.APPOINTMENT_ID = A.APPOINTMENT_ID
ORDER BY PATIENT_ID;
