-- =========================================
-- SECTION: SUBQUERIES
-- PROJECT: HEALTHCARE SQL ANALYSIS
-- =========================================

-- DOCTORS WITH APPOINTMENTS ABOVE AVERAGE
-- THIS QUERY FINDS DOCTORS WHO HAVE MORE APPOINTMENTS THAN THE AVERAGE DOCTOR.

SELECT DOCTOR_ID, COUNT(*) AS APPOINTMENT_COUNT
FROM APPOINTMENTS
GROUP BY DOCTOR_ID
HAVING COUNT(*) >
(
    SELECT AVG(APPOINTMENT_COUNT)
    FROM (
        SELECT COUNT(*) AS APPOINTMENT_COUNT
        FROM APPOINTMENTS
        GROUP BY DOCTOR_ID
    )
);

-- PATIENTS WITH VISITS ABOVE AVERAGE
-- THIS QUERY FINDS PATIENTS WHO VISITED MORE TIMES THAN THE AVERAGE PATIENT.

SELECT PATIENT_ID, COUNT(*) AS VISIT_COUNT
FROM APPOINTMENTS
GROUP BY PATIENT_ID
HAVING COUNT(*) >
(
    SELECT AVG(VISIT_COUNT)
    FROM (
        SELECT COUNT(*) AS VISIT_COUNT
        FROM APPOINTMENTS
        GROUP BY PATIENT_ID
    )
);

-- MOST RELIABLE PAYMENT METHOD
-- THIS QUERY FINDS THE PAYMENT METHOD WITH THE HIGHEST NUMBER OF SUCCESSFUL PAYMENTS.

SELECT PAYMENT_METHOD, SUCCESS_COUNT
FROM (
    SELECT PAYMENT_METHOD, COUNT(*) AS SUCCESS_COUNT
    FROM BILLING
    WHERE PAYMENT_STATUS = 'PAID'
    GROUP BY PAYMENT_METHOD
    ORDER BY SUCCESS_COUNT DESC
)
WHERE ROWNUM = 1;

-- PATIENT WITH MAXIMUM APPOINTMENTS
-- THIS QUERY IDENTIFIES THE PATIENT WHO HAS THE HIGHEST NUMBER OF APPOINTMENTS.

SELECT PATIENT_ID, APPOINTMENT_COUNT
FROM (
    SELECT PATIENT_ID, COUNT(*) AS APPOINTMENT_COUNT
    FROM APPOINTMENTS
    GROUP BY PATIENT_ID
    ORDER BY APPOINTMENT_COUNT DESC
)
WHERE ROWNUM = 1;

-- DOCTOR WITH MINIMUM APPOINTMENTS
-- THIS QUERY IDENTIFIES THE DOCTOR WHO HAS THE LEAST NUMBER OF APPOINTMENTS.

SELECT DOCTOR_ID, APPOINTMENT_COUNT
FROM (
    SELECT DOCTOR_ID, COUNT(*) AS APPOINTMENT_COUNT
    FROM APPOINTMENTS
    GROUP BY DOCTOR_ID
    ORDER BY APPOINTMENT_COUNT
)
WHERE ROWNUM = 1;

-- TREATMENTS COSTING MORE THAN AVERAGE
-- THIS QUERY FINDS TREATMENTS WHOSE COST IS ABOVE THE AVERAGE TREATMENT COST.

SELECT *
FROM TREATMENTS
WHERE COST >
(
    SELECT AVG(COST)
    FROM TREATMENTS
);

-- DOCTORS WITHOUT COMPLETED APPOINTMENTS
-- THIS QUERY IDENTIFIES DOCTORS WHO NEVER COMPLETED ANY APPOINTMENT.

SELECT DOCTOR_ID, FIRST_NAME || ' ' || LAST_NAME AS DOCTOR_NAME
FROM DOCTORS
WHERE DOCTOR_ID NOT IN
(
    SELECT DOCTOR_ID
    FROM APPOINTMENTS
    WHERE STATUS = 'COMPLETED'
);

-- PATIENTS WITHOUT COMPLETED APPOINTMENTS
-- THIS QUERY IDENTIFIES PATIENTS WHO NEVER COMPLETED ANY APPOINTMENT.

SELECT PATIENT_ID, FIRST_NAME || ' ' || LAST_NAME AS PATIENT_NAME
FROM PATIENTS
WHERE PATIENT_ID NOT IN
(
    SELECT PATIENT_ID
    FROM APPOINTMENTS
    WHERE STATUS = 'COMPLETED'
);

-- TREATMENT TYPE WITH HIGHEST REVENUE
-- THIS QUERY IDENTIFIES THE TREATMENT TYPE THAT GENERATED THE HIGHEST REVENUE.

SELECT TREATMENT_TYPE, TOTAL_REVENUE
FROM (
    SELECT TREATMENT_TYPE, SUM(COST) AS TOTAL_REVENUE
    FROM TREATMENTS
    GROUP BY TREATMENT_TYPE
    ORDER BY TOTAL_REVENUE DESC
)
WHERE ROWNUM = 1;

-- APPOINTMENT WITH HIGHEST TREATMENT COST
-- THIS QUERY IDENTIFIES THE APPOINTMENT HAVING THE HIGHEST TOTAL TREATMENT COST.

SELECT APPOINTMENT_ID, TOTAL_COST
FROM (
    SELECT APPOINTMENT_ID, SUM(COST) AS TOTAL_COST
    FROM TREATMENTS
    GROUP BY APPOINTMENT_ID
    ORDER BY TOTAL_COST DESC
)
WHERE ROWNUM = 1;

-- DOCTORS WITH HIGH CANCELLATION RATE
-- THIS QUERY CALCULATES THE CANCELLATION RATE FOR EACH DOCTOR.

SELECT DOCTOR_ID,
       COUNT(CASE WHEN STATUS = 'CANCELLED' THEN 1 END) * 100.0 / COUNT(*) AS CANCELLATION_RATE
FROM APPOINTMENTS
GROUP BY DOCTOR_ID
ORDER BY CANCELLATION_RATE DESC;

-- PATIENTS TREATED BY MULTIPLE DOCTORS
-- THIS QUERY IDENTIFIES PATIENTS WHO WERE TREATED BY MORE THAN ONE DOCTOR.

SELECT PATIENT_ID, COUNT(DISTINCT DOCTOR_ID) AS DOCTOR_COUNT
FROM APPOINTMENTS
GROUP BY PATIENT_ID
HAVING COUNT(DISTINCT DOCTOR_ID) > 1;
