-- =========================================
-- SECTION: WINDOW FUNCTIONS
-- PROJECT: HEALTHCARE SQL ANALYSIS
-- =========================================

-- RANK DOCTORS BY APPOINTMENT COUNT
-- THIS QUERY RANKS DOCTORS BASED ON THE NUMBER OF APPOINTMENTS THEY HAVE.

SELECT DOCTOR_ID,
       COUNT(*) AS APPOINTMENT_COUNT,
       RANK() OVER (ORDER BY COUNT(*) DESC) AS RANK_NO
FROM APPOINTMENTS
GROUP BY DOCTOR_ID;

-- RANK DOCTORS BY TOTAL TREATMENT COST
-- THIS QUERY RANKS DOCTORS BASED ON TOTAL TREATMENT COST GENERATED.

SELECT DOCTOR_ID,
       SUM(COST) AS TOTAL_COST,
       RANK() OVER (ORDER BY SUM(COST) DESC) AS COST_RANK
FROM APPOINTMENTS A
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY DOCTOR_ID;

-- RANK PATIENTS BY VISIT FREQUENCY
-- THIS QUERY RANKS PATIENTS BASED ON NUMBER OF VISITS.

SELECT PATIENT_ID,
       COUNT(*) AS VISIT_COUNT,
       RANK() OVER (ORDER BY COUNT(*) DESC) AS VISIT_RANK
FROM APPOINTMENTS
GROUP BY PATIENT_ID;

-- RANK TREATMENT TYPES BY AVERAGE COST
-- THIS QUERY RANKS TREATMENT TYPES BASED ON THEIR AVERAGE COST.

SELECT TREATMENT_TYPE,
       AVG(COST) AS AVG_COST,
       RANK() OVER (ORDER BY AVG(COST) DESC) AS COST_RANK
FROM TREATMENTS
GROUP BY TREATMENT_TYPE;

-- RUNNING TOTAL OF APPOINTMENTS BY DATE
-- THIS QUERY CALCULATES CUMULATIVE APPOINTMENT COUNT OVER TIME.

SELECT APPOINTMENT_DATE,
       COUNT(*) AS DAILY_COUNT,
       SUM(COUNT(*)) OVER (ORDER BY APPOINTMENT_DATE) AS CUMULATIVE_COUNT
FROM APPOINTMENTS
GROUP BY APPOINTMENT_DATE;

-- DOCTOR PERFORMANCE RANKING (COMPLETED APPOINTMENTS)
-- THIS QUERY RANKS DOCTORS BASED ON COMPLETED APPOINTMENTS.

SELECT DOCTOR_ID,
       COUNT(*) AS COMPLETED_APPOINTMENTS,
       RANK() OVER (ORDER BY COUNT(*) DESC) AS PERFORMANCE_RANK
FROM APPOINTMENTS
WHERE STATUS = 'COMPLETED'
GROUP BY DOCTOR_ID;

-- DENSE RANK DOCTORS BY EXPERIENCE
-- THIS QUERY RANKS DOCTORS BASED ON YEARS OF EXPERIENCE WITHOUT SKIPPING RANKS.

SELECT DOCTOR_ID,
       YEARS_EXPERIENCE,
       DENSE_RANK() OVER (ORDER BY YEARS_EXPERIENCE DESC) AS EXPERIENCE_RANK
FROM DOCTORS;

-- APPOINTMENT ORDER PER PATIENT
-- THIS QUERY NUMBERS EACH APPOINTMENT FOR A PATIENT IN CHRONOLOGICAL ORDER.

SELECT PATIENT_ID,
       APPOINTMENT_DATE,
       ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY APPOINTMENT_DATE) AS VISIT_ORDER
FROM APPOINTMENTS;
