-- =========================================
-- SECTION: BUSINESS INSIGHTS
-- PROJECT: HEALTHCARE SQL ANALYSIS
-- =========================================

-- WHICH DOCTOR HANDLES THE MOST PATIENTS
-- THIS QUERY IDENTIFIES THE DOCTOR WITH THE HIGHEST NUMBER OF PATIENT VISITS.

SELECT DOCTOR_ID, PATIENT_COUNT
FROM (
    SELECT DOCTOR_ID, COUNT(*) AS PATIENT_COUNT
    FROM APPOINTMENTS
    GROUP BY DOCTOR_ID
    ORDER BY PATIENT_COUNT DESC
)
WHERE ROWNUM = 1;

-- WHICH SPECIALIZATION IS MOST IN DEMAND
-- THIS QUERY IDENTIFIES THE SPECIALIZATION WITH THE HIGHEST NUMBER OF APPOINTMENTS.

SELECT SPECIALIZATION, APPOINTMENT_COUNT
FROM (
    SELECT D.SPECIALIZATION, COUNT(*) AS APPOINTMENT_COUNT
    FROM DOCTORS D
    JOIN APPOINTMENTS A
    ON D.DOCTOR_ID = A.DOCTOR_ID
    GROUP BY D.SPECIALIZATION
    ORDER BY APPOINTMENT_COUNT DESC
)
WHERE ROWNUM = 1;

-- WHAT PERCENTAGE OF APPOINTMENTS ARE CANCELLED
-- THIS QUERY CALCULATES THE OVERALL CANCELLATION RATE.

SELECT
    ROUND(
        COUNT(CASE WHEN STATUS = 'CANCELLED' THEN 1 END) * 100.0 / COUNT(*),
        2
    ) AS CANCELLED_PERCENTAGE
FROM APPOINTMENTS;

-- WHO ARE THE REPEAT PATIENTS
-- THIS QUERY IDENTIFIES PATIENTS WITH MORE THAN ONE VISIT.

SELECT PATIENT_ID, COUNT(*) AS VISIT_COUNT
FROM APPOINTMENTS
GROUP BY PATIENT_ID
HAVING COUNT(*) > 1;

-- WHICH PAYMENT METHOD IS MOST PREFERRED
-- THIS QUERY IDENTIFIES THE MOST FREQUENTLY USED PAYMENT METHOD.

SELECT PAYMENT_METHOD, TRANSACTION_COUNT
FROM (
    SELECT PAYMENT_METHOD, COUNT(*) AS TRANSACTION_COUNT
    FROM BILLING
    GROUP BY PAYMENT_METHOD
    ORDER BY TRANSACTION_COUNT DESC
)
WHERE ROWNUM = 1;

-- WHERE IS REVENUE LEAKAGE OCCURRING
-- THIS QUERY CALCULATES TOTAL REVENUE LOST DUE TO UNPAID OR FAILED BILLS.

SELECT SUM(AMOUNT) AS REVENUE_LEAKAGE
FROM BILLING
WHERE PAYMENT_STATUS IN ('Pending', 'Failed');

-- WHICH DOCTORS HAVE LOW PERFORMANCE
-- THIS QUERY IDENTIFIES DOCTORS WITH BELOW-AVERAGE COMPLETED APPOINTMENTS.

SELECT DOCTOR_ID, COUNT(*) AS COMPLETED_COUNT
FROM APPOINTMENTS
WHERE STATUS = 'Completed'
GROUP BY DOCTOR_ID
HAVING COUNT(*) < (
    SELECT AVG(CNT)
    FROM (
        SELECT COUNT(*) AS CNT
        FROM APPOINTMENTS
        WHERE STATUS = 'Completed'
        GROUP BY DOCTOR_ID
    )
);

-- WHICH TREATMENT TYPES ARE MOST EXPENSIVE ON AVERAGE
-- THIS QUERY IDENTIFIES TREATMENT TYPES WITH ABOVE-AVERAGE COST.

SELECT TREATMENT_TYPE, AVG(COST) AS AVG_COST
FROM TREATMENTS
GROUP BY TREATMENT_TYPE
HAVING AVG(COST) > (
    SELECT AVG(COST)
    FROM TREATMENTS
);

-- WHICH DOCTORS NEED WORKLOAD BALANCING
-- THIS QUERY IDENTIFIES DOCTORS WITH ABOVE-AVERAGE APPOINTMENT LOAD.

SELECT DOCTOR_ID, COUNT(*) AS APPOINTMENT_COUNT
FROM APPOINTMENTS
GROUP BY DOCTOR_ID
HAVING COUNT(*) > (
    SELECT AVG(CNT)
    FROM (
        SELECT COUNT(*) AS CNT
        FROM APPOINTMENTS
        GROUP BY DOCTOR_ID
    )
);

-- IDENTIFY OPERATIONAL BOTTLENECKS
-- THIS QUERY IDENTIFIES CANCELLED APPOINTMENTS OR APPOINTMENTS WITHOUT TREATMENTS.

SELECT COUNT(*) AS BOTTLENECK_APPOINTMENTS
FROM APPOINTMENTS A
LEFT JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
WHERE A.STATUS = 'Cancelled'
   OR T.TREATMENT_ID IS NULL;
